# config/packages/security.yml
security:
    encoders:
        App\Entity\User:
            algorithm: bcrypt
        #Symfony\Component\Security\Core\User\User: plaintext

    providers:
        our_db_provider:
            entity:
                class: App\Entity\User
                property: username
    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            # pattern:   ^/admin  => cette instruction ne ferait fonctionner l'authentification que pour les routes qui commencent par /admin
            anonymous: true
            provider:  our_db_provider
            form_login:
                login_path: login
                check_path: login
            # ...
            logout:
                path:   /logout
                target: /
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }