#index:
#    path: /
#    controller: App\Controller\DefaultController::index
logout:
  path: /logout

account_forgot_password:
  path: /security/forgot_password
  controller: App\Controller\SecurityController::forgottenPassword