#index:
#    path: /
#    controller: App\Controller\DefaultController::index
logout:
  path: /logout

account_reset_password:
  path: /security/reset_password
  controller: App\Controller\SecurityController::forgot